/**
 * Upload env model:
 *   credentials.env  — shared account secrets (once per machine)
 *   <out>/.env.batch/*.env — per-set metadata, paths, runtime IDs (generated by finalize/sync)
 *   run-line-upload merges credentials into the batch file before each Python step.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const SKILL_ROOT = resolve(SCRIPT_DIR, '..');
const PROJECT_ROOT = resolve(SKILL_ROOT, '../../..');

export const CREDENTIALS_ENV = resolve(SKILL_ROOT, 'credentials.env');
/** Legacy monolithic env; used only if credentials.env is missing or incomplete. */
const LEGACY_UPLOAD_ENV = resolve(PROJECT_ROOT, '.claude/skills/line-sticker-upload/.env');

const CREDENTIAL_KEYS = [
  'LINE_EMAIL',
  'LINE_PASSWORD',
  'LINE_CREATOR_ID',
  'GOOGLE_EMAIL',
  'GOOGLE_PASSWORD',
  'GDRIVE_PARENT_FOLDER',
] as const;

const ENV_KEY_ORDER = [
  'LINE_EMAIL',
  'LINE_PASSWORD',
  'LINE_CREATOR_ID',
  'LINE_STICKER_ID',
  'GOOGLE_EMAIL',
  'GOOGLE_PASSWORD',
  'GDRIVE_PARENT_FOLDER',
  'GDRIVE_SET_FOLDER',
  'GDRIVE_STICKER_SUBFOLDER',
  'GDRIVE_FOLDER_ID',
  'GDRIVE_SHARE_URL',
  'STICKER_TITLE_ZH',
  'STICKER_DESC_ZH',
  'STICKER_TITLE_EN',
  'STICKER_DESC_EN',
  'COPYRIGHT',
  'USE_AI',
  'SALE_START',
  'STICKER_COUNT',
  'SALE_REGION',
  'JOIN_CAMPAIGNS',
  'SOURCE_ZIP',
  'UPLOAD_ZIP',
  'SPRITE_SHEETS_DIR',
] as const;

export interface BatchEnvFields {
  setName: string;
  titleZh: string;
  descZh: string;
  titleEn: string;
  descEn: string;
}

export function parseEnv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) out[m[1]!] = m[2]!.trim();
  }
  return out;
}

export function serializeEnv(vars: Record<string, string>, header: string): string {
  const lines = [header, ''];
  for (const key of ENV_KEY_ORDER) {
    if (key in vars) lines.push(`${key}=${vars[key]}`);
  }
  return lines.join('\n') + '\n';
}

export function envHeader(setName: string): string {
  return `# LINE Creators Market — ${setName}`;
}

export function extractSetNameFromBatch(text: string): string | null {
  const m = text.match(/^# LINE Creators Market — (.+)$/m);
  return m?.[1]?.trim() ?? null;
}

/** Per-set batch env (no account secrets — those live in credentials.env). */
export function buildBatchEnvContent(fields: BatchEnvFields, relBase: string): string {
  const rel = relBase.replace(/\\/g, '/');
  return `${envHeader(fields.setName)}
# Account secrets: .claude/skills/line-sticker-maker/credentials.env (merged at upload time)

LINE_STICKER_ID=

GDRIVE_SET_FOLDER=${fields.setName}
GDRIVE_STICKER_SUBFOLDER=sticker-pack
GDRIVE_FOLDER_ID=
GDRIVE_SHARE_URL=

STICKER_TITLE_ZH=${fields.titleZh}
STICKER_DESC_ZH=${fields.descZh}
STICKER_TITLE_EN=${fields.titleEn}
STICKER_DESC_EN=${fields.descEn}

COPYRIGHT=Copyright (c) Blo0m
USE_AI=true
SALE_START=auto
STICKER_COUNT=40
SALE_REGION=all
JOIN_CAMPAIGNS=false

SOURCE_ZIP=${rel}/${fields.setName}.zip
UPLOAD_ZIP=${rel}/${fields.setName}.zip
SPRITE_SHEETS_DIR=${rel}/sprite_sheets
`;
}

export async function loadCredentials(): Promise<Record<string, string>> {
  const candidates: string[] = [];
  if (existsSync(CREDENTIALS_ENV)) candidates.push(CREDENTIALS_ENV);
  if (existsSync(LEGACY_UPLOAD_ENV)) candidates.push(LEGACY_UPLOAD_ENV);

  for (const credPath of candidates) {
    const cred = parseEnv(await readFile(credPath, 'utf8'));
    if (cred.LINE_EMAIL?.trim() && cred.LINE_CREATOR_ID?.trim()) {
      console.log(`▶ credentials: ${credPath}`);
      return cred;
    }
  }

  throw new Error(
    `No valid upload credentials (need LINE_EMAIL + LINE_CREATOR_ID). ` +
      `Copy credentials.env.example → ${CREDENTIALS_ENV}`
  );
}

/** Overlay shared credentials onto a per-job batch env (preserves runtime IDs). */
export async function mergeCredentialsIntoBatch(
  batchPath: string,
  setName: string
): Promise<void> {
  const cred = await loadCredentials();
  const batchText = await readFile(batchPath, 'utf8');
  const batch = parseEnv(batchText);
  const headerName = extractSetNameFromBatch(batchText) ?? setName;

  for (const key of CREDENTIAL_KEYS) {
    if (cred[key]) batch[key] = cred[key]!;
  }

  await writeFile(batchPath, serializeEnv(batch, envHeader(headerName)));
}

/** Merge credentials.env into batch env before upload (idempotent). */
export async function ensureBatchEnvReady(batchPath: string): Promise<void> {
  const text = await readFile(batchPath, 'utf8');
  const setName = extractSetNameFromBatch(text);
  if (!setName) {
    throw new Error(`Batch env missing header "# LINE Creators Market — {Set Name}": ${batchPath}`);
  }
  await mergeCredentialsIntoBatch(batchPath, setName);
}
