#!/usr/bin/env python3
"""Build full-glyph WOFF2 copies of the locally managed sticker fonts.

The TTF masters intentionally stay out of Git because they are also consumed by
the Node/headless pipeline and have their own distribution terms.  Browser
builds use the smaller WOFF2 copies generated by this script instead.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from fontTools.ttLib import TTFont
    from fontTools.ttLib.woff2 import compress
except ImportError as error:  # pragma: no cover - exercised by the wrapper error path
    raise SystemExit(
        "fonttools[woff] is required. Run `uv sync --locked --dev` and retry."
    ) from error


PROJECT_ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = PROJECT_ROOT / "fonts"


@dataclass(frozen=True)
class BrowserFont:
    source_file: str
    browser_file: str

    @property
    def source_path(self) -> Path:
        return FONTS_DIR / self.source_file

    @property
    def browser_path(self) -> Path:
        return FONTS_DIR / self.browser_file


BROWSER_FONTS: tuple[BrowserFont, ...] = (
    BrowserFont("LiyuShoushu.ttf", "LiyuShoushu.woff2"),
    BrowserFont("FashionBitmap16_0.092.ttf", "FashionBitmap16_0.092.woff2"),
    BrowserFont("073 TEGUSE - Kanaka Font_240705.ttf", "073 TEGUSE - Kanaka Font_240705.woff2"),
    BrowserFont("NaikaiFont-Regular-Lite.ttf", "NaikaiFont-Regular-Lite.woff2"),
)


def font_metadata(path: Path) -> tuple[dict[int, str], int]:
    """Return the Unicode cmap and glyph count needed to protect CJK coverage."""
    font = TTFont(path, lazy=True)
    try:
        return dict(font.getBestCmap() or {}), len(font.getGlyphOrder())
    finally:
        font.close()


def verify_preserved_glyphs(source: Path, browser: Path) -> None:
    """Reject a browser asset that drops any Unicode mapping or glyph."""
    source_cmap, source_glyph_count = font_metadata(source)
    browser_cmap, browser_glyph_count = font_metadata(browser)

    if source_cmap != browser_cmap:
        missing = sorted(set(source_cmap).difference(browser_cmap))
        extra = sorted(set(browser_cmap).difference(source_cmap))
        raise ValueError(
            f"{browser.name} does not preserve {source.name}'s Unicode cmap "
            f"(missing={len(missing)}, extra={len(extra)})"
        )
    if source_glyph_count != browser_glyph_count:
        raise ValueError(
            f"{browser.name} does not preserve {source.name}'s glyph count "
            f"({browser_glyph_count} != {source_glyph_count})"
        )


def is_current(source: Path, browser: Path) -> bool:
    return browser.exists() and browser.stat().st_mtime_ns >= source.stat().st_mtime_ns


def build_font(font: BrowserFont) -> None:
    source = font.source_path
    browser = font.browser_path
    temporary = browser.with_name(f"{browser.name}.tmp")

    try:
        compress(source, temporary)
        verify_preserved_glyphs(source, temporary)
        os.replace(temporary, browser)
    finally:
        if temporary.exists():
            temporary.unlink()

    saved_bytes = source.stat().st_size - browser.stat().st_size
    saved_percent = (saved_bytes / source.stat().st_size) * 100
    print(
        f"[built] {font.browser_file}: {browser.stat().st_size:,} B "
        f"({saved_percent:.1f}% smaller than {font.source_file})"
    )


def build_or_check(font: BrowserFont, *, check_only: bool) -> tuple[int, int]:
    source = font.source_path
    browser = font.browser_path

    if not source.exists():
        print(f"[skip] {font.source_file} is not present in the local font vault")
        return 0, 1

    if check_only:
        if not is_current(source, browser):
            print(f"[stale] {font.browser_file}; run `npm run fonts:build`", file=sys.stderr)
            return 1, 0
        verify_preserved_glyphs(source, browser)
        print(f"[ok] {font.browser_file} preserves cmap and glyph count")
        return 0, 0

    if is_current(source, browser):
        print(f"[current] {font.browser_file}")
        return 0, 0

    build_font(font)
    return 0, 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that local WOFF2 copies are current and preserve every glyph",
    )
    args = parser.parse_args()

    errors = 0
    skipped = 0
    for font in BROWSER_FONTS:
        font_errors, font_skipped = build_or_check(font, check_only=args.check)
        errors += font_errors
        skipped += font_skipped

    if skipped == len(BROWSER_FONTS):
        print("[info] No local TTF files found; browser previews will use their system-font fallback.")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
